application-name: sledge
socket:
    address: localhost
    port: 10200
    max_connections: 1
    message_len: 1024
daemon:
    pidfile: /tmp/sledged.pid
    workdir: '/'
logging:
    path: logs
    filename: sledge.log
    type: file-rotation
    level: DEBUG
tasks:
    -
        class: DummyTask
        description: a dummy task
    -
        class: DummyTask2
        description: another dummy task
version: 1.0.0
