application-name: sledge
socket:
    address: localhost
    port: 10200
    max_connections: 1
    message_len: 4096
logging:
    path: logs
    filename: sledge.log
    type: file-rotation
    level: DEBUG
tasks:
    -
        classname: DummyTask
        description: a dummy task
    -
        classname: DummyTask2
        description: another dummy task
    -
        classname: DummyTask3
        description: never-ending dummy task
max-runners: 4
idle-time: 0.1
