application-name: sledge
socket:
    address: localhost
    port: 10200
    max_connections: 1
    buffer_size: 4096
daemon:
    pidfile: /tmp/sledged.pid
    workdir: '/'
logging:
    path: logs
    filename: sledge.log
    type: file-rotation
    level: DEBUG
version: 1.0.0
